name: Hello
on: workflow_dispatch

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!"

  say-bye:
    runs-on: ubuntu-latest
    needs: say-hi
    steps:
      - run: echo "Goodbye after first job!"
